
const PAGE_ACCESS_TOKEN = "EAABkwwUQZC4wBAOuQHYAMk0V1G3lyv3ZCaFzLo4AMTQRuawnBhQLvZCcSPwtrnZA0XZAoOqs2zFqdkZBu0oCLofdDfiN3kZA6jtVe4aBe7biVZAHjhihShTdZAbLkn688SLRX267LtvBFeJlgHg7trBlZA5RUUQMiw4etcf6eFG38BhCXlC0ZCQTLc6";
const VERIFY_TOKEN = "PAOPAO2121";
const API_URL= "http://home.kpa.ph:5000"; 

module.exports.PAGE_ACCESS_TOKEN = PAGE_ACCESS_TOKEN;
module.exports.VERIFY_TOKEN = VERIFY_TOKEN;
module.exports.API_URL = API_URL;
