
const PAGE_ACCESS_TOKEN = "EAAYYmSZAZBhIkBACqwsWHRjX7P9ko35EPBZBiTnZAD2DlSBuZCtJJZByDHx1ZCMsyLFSEbocLP2ZCKQXZBVbOOphlmp8Hiv8RRounnGiVrAMcY6fvBhORI7H2HERJbeI31aTQ4KtSSioId02egzM5QSJOQ8nVXzHxCLxElpv1EU4oJwSMQDLAqUyA";
const VERIFY_TOKEN = "PAOPAO2121";
const API_URL= "http://home.kpa.ph:5000"; 

module.exports.PAGE_ACCESS_TOKEN = PAGE_ACCESS_TOKEN;
module.exports.VERIFY_TOKEN = VERIFY_TOKEN;
module.exports.API_URL = API_URL;
